Update ga

diff --git a/.github/workflows/deploy-to-aws.yml b/.github/workflows/deploy-to-aws.yml
--- a/.github/workflows/deploy-to-aws.yml
+++ b/.github/workflows/deploy-to-aws.yml
@@ -145,47 +145,47 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Configure AWS credentials
-        uses: Moulick/configure-multiple-aws-roles@v4
-        with:
-          role-to-assume: ${{ vars.ecs_rollout_role }}
-          profile: uksa-mys-dev-env
-          aws-region: eu-west-2
+      # - name: Configure AWS credentials
+      #   uses: Moulick/configure-multiple-aws-roles@v4
+      #   with:
+      #     role-to-assume: ${{ vars.ecs_rollout_role }}
+      #     profile: uksa-mys-dev-env
+      #     aws-region: eu-west-2
 
-      - name: Setup api-e2e service
-        run: |
-          COMMAND_ID=$(aws ssm send-command \
-          --instance-ids ${{ vars.bastion_instance_id }} \
-          --document-name "AWS-RunShellScript" \
-          --parameters commands=["bash /home/ec2-user/e2e-rollover.sh"] \
-          --region eu-west-2 \
-          --profile uksa-mys-dev-env \
-          --query "Command.CommandId" \
-          --output text)
+      # - name: Setup api-e2e service
+      #   run: |
+      #     COMMAND_ID=$(aws ssm send-command \
+      #     --instance-ids ${{ vars.bastion_instance_id }} \
+      #     --document-name "AWS-RunShellScript" \
+      #     --parameters commands=["bash /home/ec2-user/e2e-rollover.sh"] \
+      #     --region eu-west-2 \
+      #     --profile uksa-mys-dev-env \
+      #     --query "Command.CommandId" \
+      #     --output text)
         
-          while true; do
-            STATUS=$(aws ssm list-command-invocations \
-              --command-id "$COMMAND_ID" \
-              --details \
-              --region eu-west-2 \
-              --profile uksa-mys-dev-env \
-              --query "CommandInvocations[0].Status" \
-              --output text)
+      #     while true; do
+      #       STATUS=$(aws ssm list-command-invocations \
+      #         --command-id "$COMMAND_ID" \
+      #         --details \
+      #         --region eu-west-2 \
+      #         --profile uksa-mys-dev-env \
+      #         --query "CommandInvocations[0].Status" \
+      #         --output text)
           
-            echo "Command status: $STATUS"
+      #       echo "Command status: $STATUS"
           
-            [[ "$STATUS" == "Success" || "$STATUS" == "Failed" ]] && break
+      #       [[ "$STATUS" == "Success" || "$STATUS" == "Failed" ]] && break
           
-            sleep 5
-          done
+      #       sleep 5
+      #     done
           
-          aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id ${{ vars.bastion_instance_id }} \
-          --region eu-west-2 \
-          --profile uksa-mys-dev-env \
-          --query "StandardOutputContent" \
-          --output text
+      #     aws ssm get-command-invocation \
+      #     --command-id "$COMMAND_ID" \
+      #     --instance-id ${{ vars.bastion_instance_id }} \
+      #     --region eu-west-2 \
+      #     --profile uksa-mys-dev-env \
+      #     --query "StandardOutputContent" \
+      #     --output text
         
 
       - name: Execute Backend E2E API tests
@@ -205,14 +205,14 @@ jobs:
           files: |
             **/newman-run-*.xml
 
-      - name: Shutdown api-e2e service
-        if: always() || failure()
-        run: |
-          aws ssm send-command \
-                    --instance-ids ${{ vars.bastion_instance_id }} \
-                    --document-name "AWS-RunShellScript" \
-                    --parameters commands=["bash /home/ec2-user/e2e-shutdown.sh"] \
-                    --region eu-west-2 \
-                    --profile uksa-mys-dev-env \
-                    --query "Command.CommandId" \
-                    --output text
+      # - name: Shutdown api-e2e service
+      #   if: always() || failure()
+      #   run: |
+      #     aws ssm send-command \
+      #               --instance-ids ${{ vars.bastion_instance_id }} \
+      #               --document-name "AWS-RunShellScript" \
+      #               --parameters commands=["bash /home/ec2-user/e2e-shutdown.sh"] \
+      #               --region eu-west-2 \
+      #               --profile uksa-mys-dev-env \
+      #               --query "Command.CommandId" \
+      #               --output text
